site_name: Vexo
site_url: https://vexo.ai
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  palette:
    scheme: slate
    primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.path
    - toc.integrate
extra_css:
  - assets/stylesheets/extra.css
repo_url: https://github.com/VexoAI/vexo
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vexoAI
    - icon: fontawesome/brands/github
      link: https://github.com/VexoAI/
copyright: A project by <a href="https://github.com/fvdb/">Frank van den Brink</a>

# Page tree
nav:
  - index.md
  - terminology.md
  - installation.md
  - changelog.md
  - Chains:
    - chains/introduction.md
    - Standard Chains:
        - chains/standard-chains/README.md
        - chains/standard-chains/language-model-chain.md
        - chains/standard-chains/webtext-chain.md
        - chains/standard-chains/sequential-chain.md
        - chains/standard-chains/caching-chain.md
    - chains/custom-chains.md
    - chains/events.md
    - chains/testing-with-chains.md
  - Language Models:
    - language-models/getting-started.md
    - Available Models:
        - language-models/available-models/README.md
        - language-models/available-models/openai-chat.md
    - language-models/custom-models.md
    - language-models/events.md
    - language-models/testing-with-models.md
  - Prompts:
    - prompts/simple-prompts.md
    - prompts/templates.md
  - Agents:
    - agents/introduction.md
  - Advanced Topics:
    - advanced/event-handling.md
