site_name: Vexo
site_url: https://vexo.ai
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  palette:
    scheme: slate
    primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
extra_css:
  - assets/stylesheets/extra.css
repo_url: https://github.com/VexoAI/vexo
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vexoAI
    - icon: fontawesome/brands/github
      link: https://github.com/VexoAI/
copyright: A project by <a href="https://github.com/fvdb/">Frank van den Brink</a>

# Page tree
nav:
  - index.md
  - Getting Started:
    - getting-started/what-is-vexo.md
    - getting-started/terminology.md
    - getting-started/installation.md
    - getting-started/changelog.md
  - Reference:
    - Chains:
      - reference/chains/introduction.md
      - Standard Chains:
          - reference/chains/standard-chains/README.md
          - reference/chains/standard-chains/language-model-chain.md
          - reference/chains/standard-chains/webtext-chain.md
          - reference/chains/standard-chains/sequential-chain.md
          - reference/chains/standard-chains/caching-chain.md
      - reference/chains/custom-chains.md
      - reference/chains/events.md
      - reference/chains/testing-with-chains.md
    - Language Models:
      - reference/language-models/getting-started.md
      - Available Models:
          - reference/language-models/available-models/README.md
          - reference/language-models/available-models/openai-chat.md
      - reference/language-models/custom-models.md
      - reference/language-models/events.md
      - reference/language-models/testing-with-models.md
    - Prompts:
      - reference/prompts/simple-prompts.md
      - reference/prompts/templates.md
    - Agents:
      - reference/agents/introduction.md
    - Advanced Topics:
      - reference/advanced/event-handling.md
