site_name: Vexo
site_url: https://vexo.ai
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  palette:
    scheme: slate
    primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.path
    - toc.integrate
extra_css:
  - assets/stylesheets/extra.css
repo_url: https://github.com/VexoAI/vexo
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vexoAI
    - icon: fontawesome/brands/github
      link: https://github.com/VexoAI/
copyright: A project by <a href="https://github.com/fvdb/">Frank van den Brink</a>

# Page tree
nav:
  - What is Vexo?: index.md
  - Terminology: terminology.md
  - Installation: installation.md
  - Changelog: changelog.md
  - Chains:
    - Introduction: chains/introduction.md
    - Standard Chains: chains/standard-chains/README.md
    - Standard - Language Model Chain: chains/standard-chains/language-model-chain.md
    - Standard - WebText Chain: chains/standard-chains/webtext-chain.md
    - Standard - Sequential Chain: chains/standard-chains/sequential-chain.md
    - Standard - Caching Chain: chains/standard-chains/caching-chain.md
    - Custom Chains: chains/custom-chains.md
    - Events: chains/events.md
    - Testing with Chains: chains/testing-with-chains.md
  - Language Models:
    - Getting Started: language-models/getting-started.md
    - Available Models: language-models/available-models/README.md
    - Available - OpenAI Chat: language-models/available-models/openai-chat.md
    - Custom Models: language-models/custom-models.md
    - Events: language-models/events.md
    - Testing with Models: language-models/testing-with-models.md
  - Prompts:
    - Simple Prompts: prompts/simple-prompts.md
    - Templates: prompts/templates.md
  - Agents:
    - Introduction: agents/introduction.md
  - Advanced Topics:
    - Event Handling: advanced/event-handling.md
