site_name: Vexo
site_url: https://vexo.ai
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: black
  font:
    text: Inter
    code: Menlo
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - content.code.copy
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/highlight.css
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mike:
      canonical_version: latest
watch:
  - overrides
  - navigation.yml
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vexoAI
    - icon: fontawesome/brands/github
      link: https://github.com/VexoAI/
copyright: A project by <a href="https://twitter.com/fvdb/">Frank van den Brink</a>

INHERIT: navigation.yml
